<?php
// Base API configuration and helpers
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization");
header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

// Config will be generated by install.php, but we provide a fallback message if not found
if (!file_exists(__DIR__ . '/config.php')) {
    http_response_code(500);
    echo json_encode(['error' => 'Aplikasi belum diinstall. Jalankan install.php terlebih dahulu.']);
    exit;
}

require_once __DIR__ . '/config.php';

function sendResponse($data, $statusCode = 200) {
    http_response_code($statusCode);
    echo json_encode($data);
    exit;
}

function sendError($message, $statusCode = 400) {
    http_response_code($statusCode);
    echo json_encode(['error' => $message]);
    exit;
}

/**
 * Baca tenant_id dari header X-Tenant-ID yang dikirim frontend.
 * Jika tidak ada, kirim error 401.
 */
function getTenantId() {
    $tenantId = $_SERVER['HTTP_X_TENANT_ID'] ?? null;
    if (!$tenantId || !is_numeric($tenantId)) {
        http_response_code(401);
        echo json_encode(['error' => 'Sesi tidak valid. Silakan login kembali.']);
        exit;
    }
    return (int) $tenantId;
}
